#!/bin/bash
#SBATCH --partition=day
#SBATCH --job-name=model1a
#SBATCH --ntasks=1 --nodes=1
#SBATCH --mem-per-cpu=6000 
#SBATCH --time=12:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=annie.chen@yale.edu

module load Langs/Python/2.7-anaconda   
python tempa.py > output.txt
