#!/bin/bash
#SBATCH --partition=gpu
#SBATCH --job-name=model1i
#SBATCH --ntasks=1 --nodes=1
#SBATCH --mem-per-cpu=9000 
#SBATCH --time=20:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=annie.chen@yale.edu

module load Langs/Python/2.7-anaconda   
python tempi.py > ioutput.txt
